name: PlatformIO Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: yourdockerhubusername/yourimagename:latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test Native
        run: platformio test -e native

      - name: Build and Test ESP32
        run: platformio run -e esp32dev
        # Add additional steps for deploying or testing with PlatformIO remote development tools if necessary